import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "../../lib/utils";
import "../globals.css";
import SideBar from "@/components/bookmarks/sidebar";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("hello from child layout");

  return (
    <html lang="en" className="w-full h-full">
      <body className={cn(inter.className, "bg-background w-full h-full")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-full relative h-full bg-background min-h-screen pl-4">
            <SideBar />
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
