import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { cn } from "../../lib/utils";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("hello from child layout");

  return (
    <html lang="en" className="w-full h-full">
      <body className={cn(inter.className, "bg-background w-full h-full")}>
        <main className="w-full relative h-full bg-background min-h-screen pl-4">
          {/* side bar */}
          <div className="absolute left-0 top-0 bottom-0 w-2/12 bg-secondary border-r max-w-screen-sm min-w-72 border-border rounded-r-md -translate-x-[98%] hover:translate-x-0 transition-all duration-200"></div>
          {children}
        </main>
      </body>
    </html>
  );
}
